### ISSUE TITLE
Multi-pressed keys

### ISSUE THREAD

**Issue by TildaDares** [andrewjh271/calculator#1]
Hi I'd like to know how you were able to handle keys that are multi-pressed like the percent key (that is if you want to tell me).

**Comment by andrewjh271** [comment]
Hi,
If you console.log the key value, say for Shift-5 to get %, you will see both Shift and % come up. So getting the % isn't too hard, but you may have an issue with filtering out the combination because Shift comes first. You can see how I did it toward the beginning of my .js file. Good luck!
